apiVersion: apps/v1
kind: Deployment
metadata:
  name: proctorbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proctorbackend
  template:
    metadata:
      labels:
        app: proctorbackend
    spec:
      containers:
        - name: proctorbackend
          image: proctordev.azurecr.io/proctorbackend:$tag
          imagePullPolicy: Always                                                         
          ports:
          - containerPort: 3002
      imagePullSecrets:
        - name: mysecret
        env:
          