apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: lxpdevqa.azurecr.io/user:$tag
          imagePullPolicy: Always
          env:
          - name:  'UPSKILL_ADMIN_URL' 
            value: 'https://upskilladmin.lntedutech.com/'
          - name:  'UPSKILL_LEARNER_URL' 
            value: 'https://upskill.lntedutech.com/'
          - name:  'UPSKILL_SUPPORT_MAIL' 
            value: 'mailto:upskill.support@lntedutech.com'
          - name:  'RECAPTCHA_SECRET_KEY' 
            value: '6LfFoOccAAAAADiqVaCeBi5wK9ShZBYE3BwR9Cdq'   
          - name: "SMARTSERVICEURL"
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: dataservice
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: USER_DB_URL
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: REDIS_PORT
          - name: REDIS
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: REDIS
          - name: REDISCACHEKEY
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: REDISCACHEKEY
          - name: course_service
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: course
          - name: user_service
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: user
          - name: AUDIT_URL
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: audit_log
          - name: ELASTICSEARCH
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: ELASTICSEARCH
          - name: NOTIFICATION_URL
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: NOTIFICATION_URL
          - name: ELASTIC_SEARCH_LOGGING_URL
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: ELASTIC_SEARCH_LOGGING_URL
          - name: APMLOGGER
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: APMLOGGER
          - name: dataserviceURL
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: socketio
          - name: ELASTICSEARCH
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: ELASTICSEARCH
          - name: ELASTICSEARCH_PORT
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: ELASTICSEARCHPORT
          - name: COURSES_LINK
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: course_url
          - name: MAIL_LINK
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: app
          - name: KAUSHALYA_MAIL_LINK
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: kaushalya
          - name: UPDATE_EMAIL
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: facade
          - name: NODEBB_URL
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: nodeBB
          - name: NODEBB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: NODEBB_USERNAME
          - name: NODEBB_KEY
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: NODEBB_KEY
          - name: NODEBB_UID
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: NODEBB_UID
          - name: NOTIFICATION_URL
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: NOTIFICATION_URL
          - name: ADMIN_MAIL_LINK
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: admin_url
          - name: PORTAL_URL
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: PORTAL_URL
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: ENVIRONMENT
          - name: PORT
            value: '3001'
          - name: accountKey
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: accountKey
          - name: accountName
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: accountName
          - name: UPSKILL_ADMIN_URL
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: UPSKILL_ADMIN_URL
          - name: UPSKILL_LEARNER_URL
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: UPSKILL_LEARNER_URL
          - name: UPSKILL_SUPPORT_MAIL
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: UPSKILL_SUPPORT_MAIL
          - name: ELASTICSEARCH_SERVICE
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: ELASTICSEARCH_SERVICE
          - name: SMARTSERVICEURL
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: SMARTSERVICEURL
          - name: SENDGRID_TOKEN
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: SENDGRID_TOKEN
          - name: lmsBaseUrl
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: lmsBaseUrl
          - name: stepUI
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: stepUI
          - name: stepURL
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: stepURL                                                    
          - name: enableRecaptcha
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: enableRecaptcha
          - name: emailFooterYear
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: emailFooterYear
          - name: service_authToken
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: service_authToken 
          - name: sasToken
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: sasToken  
          - name: Mcert_UserDB_url
            valueFrom:
              configMapKeyRef:
                name: allconfig
                key: Mcert_UserDB_url                                                                         
          ports:
          - containerPort: 3001
      imagePullSecrets:
        - name: mysecret