apiVersion: apps/v1
kind: Deployment
metadata:
  name: proaiservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proaiservice
  template:
    metadata:
      labels:
        app: proaiservice
    spec:
      containers:
        - name: proaiservice
          image: proctordev.azurecr.io/proaiservice:$tag
          imagePullPolicy: Always
          env:
          - name: DATA_SERVICE_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: proctor-dev-env
                key: DATA_SERVICE_ENDPOINT  
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: proctor-dev-env
                key: MONGO_URI                                                              
          ports:
          - containerPort: 3001
      imagePullSecrets:
        - name: mysecret