apiVersion: v1
kind: Service
metadata:
  name: proctorbackend
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: proctorbackend1
  ports:
    - port: 3002
      targetPort: 3002
  type: LoadBalancer